#!/usr/bin/env python3
"""Pin the CISA KEV status of every CVE the repository cites, and gate the prose.

    python scripts/cve_status.py            # gate, writes nothing
    python scripts/cve_status.py --check    # same, explicit
    python scripts/cve_status.py --refresh  # re-pin schema/cve-status.json (network)
    python scripts/cve_status.py --refresh --kev-file known_exploited_vulnerabilities.json

"On CISA KEV" is a claim a responder acts on - it moves a finding up the queue
and it is the first thing a manager asks. The repository made it about Ray
CVE-2023-48022 in a rule header while the investigation guide said, correctly,
that the CVE is not in the catalog. Two files disagreeing about a public list is
a defect the list itself can settle, so this pins the list and checks the text
against it, the same way validate_techniques.py pins ATLAS and ATT&CK.

Same shape as that script: validation is offline against a vendored pin, and
--refresh is the only thing that touches the network, so a KEV addition shows
up in review as a diff rather than silently changing what CI enforces.

The gate fails when:
  - a CVE is cited anywhere and is missing from the pin (run --refresh)
  - a line says a CVE is on CISA KEV and the pin says it is not
It does not fail on a KEV-listed CVE that nobody calls KEV - that is an
omission, reported, not a false statement.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPO = ROOT.parent
PINNED = ROOT / "schema" / "cve-status.json"
KEV_URL = ("https://www.cisa.gov/sites/default/files/feeds/"
           "known_exploited_vulnerabilities.json")

CVE = re.compile(r"\bCVE-\d{4}-\d{4,7}\b")
# "CISA KEV", "KEV-listed", "on the KEV catalog". VulnCheck runs its own KEV
# list, and a line that names it is talking about that list, not CISA's.
KEV_CLAIM = re.compile(r"\bKEV\b")
NOT_CISA = re.compile(r"VulnCheck|not (?:in|on)|does not appear|isn't|is not", re.I)

SURFACES = ["MAPPINGS.md", "README.md", "playbooks/*.json", "0[0-9]-*/*",
            "artifacts/detections/**/*", "artifacts/catalog/*.yml",
            "artifacts/case-studies/*.yml", "artifacts/intel/**/*.yml",
            "docs/*.md", "artifacts/README.md"]


def lines():
    seen = set()
    for pattern in SURFACES:
        for f in sorted(REPO.glob(pattern)):
            if f in seen or not f.is_file():
                continue
            seen.add(f)
            try:
                text = f.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            for n, line in enumerate(text.splitlines(), 1):
                yield f.relative_to(REPO), n, line


def claimed(line: str, at: int, above: str = "") -> str | None:
    """The CVE a KEV token on this line is about: the nearest one before it.

    "CVE-2025-3248 (CISA KEV), CVE-2026-5027" makes a claim about the first CVE
    only. Reading every CVE on the line as claimed flagged the second as a false
    KEV statement, which it is not.
    """
    before = [m for m in CVE.finditer(line) if m.end() <= at]
    if before:
        return before[-1].group(0)
    earlier = CVE.findall(above)
    if earlier:
        return earlier[-1]
    after = CVE.search(line, at)
    return after.group(0) if after else None


def cited() -> set[str]:
    return {c for _, _, line in lines() for c in CVE.findall(line)}


def refresh(kev_file: Path | None) -> dict:
    if kev_file:
        kev = json.loads(kev_file.read_text(encoding="utf-8"))
    else:
        with urllib.request.urlopen(KEV_URL, timeout=120) as r:
            kev = json.loads(r.read())
    listed = {v["cveID"]: v for v in kev.get("vulnerabilities", [])}
    out = {}
    for c in sorted(cited()):
        v = listed.get(c)
        out[c] = ({"cisa_kev": True, "date_added": v.get("dateAdded", ""),
                   "vendor": v.get("vendorProject", ""), "product": v.get("product", ""),
                   "ransomware": v.get("knownRansomwareCampaignUse", "")}
                  if v else {"cisa_kev": False})
    return {
        "_comment": "Generated by scripts/cve_status.py --refresh. Do not hand-edit.",
        "retrieved": date.today().isoformat(),
        "source": KEV_URL,
        "catalog_version": kev.get("catalogVersion", ""),
        "cves": out,
    }


def check() -> list[str]:
    if not PINNED.exists():
        return [f"{PINNED.relative_to(ROOT)} is missing - run --refresh"]
    pin = json.loads(PINNED.read_text(encoding="utf-8"))["cves"]
    problems = []
    for c in sorted(cited() - set(pin)):
        problems.append(f"{c} is cited but not pinned - run cve_status.py --refresh")
    # A KEV token is about the nearest CVE before it - on the same line, or on
    # the lines just above when the sentence wraps (the Ray rule said "KEV-listed
    # by CISA" five lines below the CVE it meant). Only when nothing precedes it
    # does the nearest CVE after it on the same line count.
    by_file: dict[Path, list[tuple[int, str]]] = {}
    for rel, n, line in lines():
        by_file.setdefault(rel, []).append((n, line))
    for rel, rows in by_file.items():
        for i, (n, line) in enumerate(rows):
            if NOT_CISA.search(line):
                continue
            for k in KEV_CLAIM.finditer(line):
                c = claimed(line, k.start(), " ".join(l for _, l in rows[max(0, i - 8):i]))
                if c and c in pin and not pin[c]["cisa_kev"]:
                    problems.append(f"{rel}:{n}: says {c} is on CISA KEV; the pinned "
                                    f"catalog does not list it")
    return sorted(set(problems))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--refresh", action="store_true")
    ap.add_argument("--kev-file", type=Path,
                    help="read the KEV JSON from a local copy (e.g. a cisagov/kev-data clone)")
    args = ap.parse_args()
    if args.refresh:
        data = refresh(args.kev_file)
        with open(PINNED, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
        n = sum(1 for v in data["cves"].values() if v["cisa_kev"])
        print(f"pinned {len(data['cves'])} cited CVEs, {n} on CISA KEV "
              f"(catalog {data['catalog_version']})")
        return 0
    problems = check()
    for p in problems:
        print(f"[KEV]    {p}")
    print(f"\n{len(problems)} problem(s).")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
