#!/usr/bin/env python3
"""Generate the Contents block in README.md from the catalog, and gate it.

    python scripts/readme_counts.py            # rewrite the block
    python scripts/readme_counts.py --check    # fail if stale, write nothing

Every number in that block was hand-typed and every one of them drifted. The
table said 44 tools against 51, 258 artifacts against 601, 3 case studies
against 14; the risk and confidence lines both still summed to 44. A reader has
no way to tell a stale count from a current one, and the counts are the first
thing in the file.

This is the third time the same failure has been fixed here - CLAUDE.md's "what
is next" section and issue #8 both carried totals that had silently drifted -
so it is fixed the same way the feeds are: derived from the catalog, rewritten
by a script, and gated in CI so it cannot rot again.

Definitions are deliberately explicit, because "artifacts" and "locations" can
each mean two things and the old block never said which:

  tools        one catalog/*.yml file
  artifacts    every row the catalog yields - the same row model the site
               counts, so this number matches `build_site.py --check`
  credential   rows of class credential (not distinct files on disk)
  mcp config   rows of class mcp-config
  sigma rules  detections/sigma/*.yml only, which is why it reads 12 and not
               the repo-wide 68 in the root README - that one counts YARA and
               Suricata across the 0N-* directories too. Both are correct; they
               count different things, and the block now says so.
"""
from __future__ import annotations

import argparse
import glob
import sys
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
START = "<!-- counts:start - generated by scripts/readme_counts.py, do not edit -->"
END = "<!-- counts:end -->"

ROW_KEYS = ("disk", "registry", "network", "process", "eventlog")


def counts() -> dict:
    entries = [yaml.safe_load(Path(f).read_text(encoding="utf-8"))
               for f in sorted(glob.glob(str(ROOT / "catalog" / "*.yml")))]

    rows = credentials = mcp = 0
    for entry in entries:
        artifacts = entry.get("artifacts") or {}
        for key in ROW_KEYS:
            rows += len(artifacts.get(key) or [])
        credentials += len(entry.get("credentials") or [])
        mcp += len(entry.get("mcp") or [])

    return {
        "entries": entries,
        "tools": len(entries),
        "artifacts": rows + credentials + mcp,
        "credentials": credentials,
        "mcp": mcp,
        "sigma": len(glob.glob(str(ROOT / "detections" / "sigma" / "*.yml"))),
        "cases": len(glob.glob(str(ROOT / "case-studies" / "*.yml"))),
    }


def render(c: dict) -> str:
    entries = c["entries"]
    risk = Counter(e.get("risk", "?") for e in entries)
    conf = Counter(e.get("confidence", "?") for e in entries)
    cats = Counter(e.get("category", "?") for e in entries)

    def ramp(counter: Counter, order: tuple) -> str:
        # Middle dot, matching the separator the block already used. The file is
        # written UTF-8; only a Windows console mangles it, and nothing reads
        # this through one.
        return " · ".join(f"{counter[k]} {k}" for k in order if counter[k])

    lines = [
        START,
        "",
        "| | Count |",
        "|---|---|",
        f"| Catalogued tools | **{c['tools']}** |",
        f"| Documented artifacts | **{c['artifacts']}** |",
        f"| Credential locations | **{c['credentials']}** |",
        f"| MCP config locations | **{c['mcp']}** |",
        f"| Sigma detection rules | **{c['sigma']}** |",
        f"| Case studies | **{c['cases']}** |",
        "",
        "Artifacts counts every row the catalog yields, so it matches the site and",
        "`build_site.py --check`. Sigma rules counts `detections/sigma/` only - the",
        "root README's larger figure counts YARA and Suricata across the `0N-*`",
        "directories as well. Both are right about different things.",
        "",
        f"**Risk:** {ramp(risk, ('critical', 'high', 'medium', 'low'))}",
        "",
        f"**Confidence:** {ramp(conf, ('high', 'medium', 'low'))}",
        "",
        "Categories: " + ", ".join(f"{k} ({v})" for k, v in cats.most_common()),
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report drift and write nothing")
    args = ap.parse_args()

    text = README.read_text(encoding="utf-8")
    block = render(counts())

    if START not in text or END not in text:
        print(f"{README.name} has no counts block - add the markers first:",
              file=sys.stderr)
        print(f"  {START}\n  {END}", file=sys.stderr)
        return 1

    head, _, rest = text.partition(START)
    _, _, tail = rest.partition(END)
    updated = head + block + tail

    if updated == text:
        print("README counts are current.")
        return 0

    if args.check:
        print("::error::artifacts/README.md counts are stale. "
              "Run scripts/readme_counts.py and commit.", file=sys.stderr)
        print("\n1 problem(s).")
        return 1

    with open(README, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print(f"rewrote the counts block in {README.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
