"""Triage script templates the site fills in from a collection plan.

Two self-contained scripts, PowerShell for Windows and POSIX-leaning bash for
macOS and Linux, with no dependency beyond what ships with the OS. The site
replaces __TARGETS__ with one line per picked artifact and __META__ with the plan
details; nothing else in the template varies, so what runs on a host is
reviewable here rather than being assembled out of string fragments in a browser.

The rules both scripts keep are collect_ai_artifacts.py's, for the same reasons:
  - read-only. Nothing is written to a source location; copies keep timestamps.
  - chain of custody. Every file is SHA-256 hashed at the source and re-hashed
    after copy; the manifest records operator, host, UTC window and the hash of
    the script itself, and is hashed in turn.
  - least collection. A credential row records metadata and a hash, not the
    secret, unless the operator passes -CollectSecrets / --collect-secrets.
  - volatile first. Process and socket state is captured before any file copy,
    because it is the only thing on the host that a copy step can change.
"""

PS1 = r'''<#
  AI agent artifact triage - generated by ai-dfir-toolkit
  __META__

  Run elevated to reach every user profile. Read-only against the sources.
  Usage:
    powershell -ExecutionPolicy Bypass -File .\__NAME__.ps1 -CaseId IR-001 -Operator you
    [-Out D:\evidence] [-RepoPath C:\src\app,C:\src\other] [-HomePath C:\Users\alice]
    [-CollectSecrets] [-MaxFileMB 512]
#>
param(
  [string]$CaseId = "case",
  [string]$Operator = $env:USERNAME,
  [string]$Out = (Join-Path $env:SystemDrive "AIDFIR"),
  [string[]]$RepoPath = @(),
  [string[]]$HomePath = @(),
  [switch]$CollectSecrets,
  [int]$MaxFileMB = 512
)
$ErrorActionPreference = "Continue"
$ProgressPreference = "SilentlyContinue"
$started = (Get-Date).ToUniversalTime()
$stamp = $started.ToString("yyyyMMddTHHmmssZ")
$root = Join-Path $Out ("{0}_{1}_{2}" -f $CaseId, $env:COMPUTERNAME, $stamp)
$files = Join-Path $root "files"
$live = Join-Path $root "live"
New-Item -ItemType Directory -Force -Path $files, $live | Out-Null
$manifest = New-Object System.Collections.Generic.List[object]
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { Write-Warning "Not elevated: other users' profiles and some logs will be unreadable." }

# Every profile by default; -HomePath narrows collection to the named ones.
$homes = if ($HomePath.Count) { $HomePath } else {
  @(Get-ChildItem (Join-Path $env:SystemDrive "Users") -Directory -Force -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notin @("Public","Default","Default User","All Users") } | ForEach-Object { $_.FullName }) }

function Add-Row($t, $path, $status, $note, $size, $mtime, $sha, $dest) {
  $manifest.Add([pscustomobject]@{
    anchor=$t.a; tool=$t.tool; class=$t.c; template=$t.p; path=$path; status=$status;
    size=$size; mtime_utc=$mtime; sha256=$sha; dest=$dest; note=$note })
}

function Expand-Template($tmpl) {
  if ($tmpl -like "*{HOME}*") { return $homes | ForEach-Object { $tmpl.Replace("{HOME}", $_) } }
  if ($tmpl -like "*{REPO}*") { return $RepoPath | ForEach-Object { $tmpl.Replace("{REPO}", $_.TrimEnd("\")) } }
  return @($tmpl)
}

# Every credential location the catalog knows for this OS, not only the picked
# ones. A directory row (~/.claude/) otherwise sweeps a token file into the copy
# and defeats the hash-only rule for secrets.
$secretPatterns = @(
__SECRETS__
)
function Test-Secret($path) {
  foreach ($p in $secretPatterns) { if ($path -like $p) { return $true } }
  return $false
}

function Collect-File($t, $f) {
  $size = $f.Length; $mtime = $f.LastWriteTimeUtc.ToString("o")
  $isSecret = $t.s -or (Test-Secret $f.FullName)
  $sha = ""
  if ($size -le ($MaxFileMB * 1MB)) {
    try { $sha = (Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256 -ErrorAction Stop).Hash.ToLower() }
    catch { Add-Row $t $f.FullName "error" ("hash: " + $_.Exception.Message) $size $mtime "" ""; return }
  } else {
    Add-Row $t $f.FullName "metadata-only" ("larger than " + $MaxFileMB + " MB") $size $mtime "" ""; return
  }
  if ($isSecret -and -not $CollectSecrets) {
    Add-Row $t $f.FullName "hashed-only" "credential: pass -CollectSecrets to copy" $size $mtime $sha ""; return
  }
  $dest = Join-Path $files ($f.FullName -replace "^([A-Za-z]):", '$1')
  try {
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    Copy-Item -LiteralPath $f.FullName -Destination $dest -Force -ErrorAction Stop
    (Get-Item -LiteralPath $dest).CreationTimeUtc = $f.CreationTimeUtc
    (Get-Item -LiteralPath $dest).LastWriteTimeUtc = $f.LastWriteTimeUtc
    $check = (Get-FileHash -LiteralPath $dest -Algorithm SHA256).Hash.ToLower()
    $status = if ($check -eq $sha) { "copied" } else { "copied-hash-mismatch" }
    Add-Row $t $f.FullName $status "" $size $mtime $sha $dest.Substring($root.Length + 1)
  } catch {
    # A file the application holds open (a SQLite store, a live log) will not
    # copy. The hash above still proves what was there; image the volume or
    # use a VSS snapshot for the content.
    Add-Row $t $f.FullName "locked" $_.Exception.Message $size $mtime $sha ""
  }
}

function Collect-Path($t) {
  foreach ($p in (Expand-Template $t.p)) {
    $items = @(Get-Item -Path $p -Force -ErrorAction SilentlyContinue)
    if (-not $items) { Add-Row $t $p "absent" "" "" "" "" ""; continue }
    foreach ($i in $items) {
      if ($i.PSIsContainer) {
        Get-ChildItem -LiteralPath $i.FullName -Recurse -File -Force -ErrorAction SilentlyContinue |
          ForEach-Object { Collect-File $t $_ }
      } else { Collect-File $t $i }
    }
  }
}

function Collect-Registry($t) {
  $safe = ($t.p -replace '[\\/:*?"<>|]', "_")
  $keys = @($t.p)
  if ($t.p -like "HKCU\*" -and $isAdmin) {
    # HKCU is only the operator's hive. Every loaded user hive is under HKU.
    $keys = @(Get-ChildItem "Registry::HKEY_USERS" -ErrorAction SilentlyContinue |
      Where-Object { $_.PSChildName -match "^S-1-5-21-[\d-]+$" } |
      ForEach-Object { "HKU\" + $_.PSChildName + $t.p.Substring(4) })
  }
  foreach ($k in $keys) {
    $dest = Join-Path $live ("reg_" + ($k -replace '[\\/:*?"<>|]', "_") + ".reg")
    if ($t.s -and -not $CollectSecrets) {
      $exists = Test-Path ("Registry::" + $k)
      Add-Row $t $k ($(if ($exists) { "present-not-exported" } else { "absent" })) "credential values: pass -CollectSecrets to export" "" "" "" ""
      continue
    }
    & reg.exe export $k $dest /y 2>$null | Out-Null
    if (Test-Path $dest) { Add-Row $t $k "exported" "" (Get-Item $dest).Length "" (Get-FileHash $dest -Algorithm SHA256).Hash.ToLower() $dest.Substring($root.Length + 1) }
    else { Add-Row $t $k "absent" "" "" "" "" "" }
  }
}

function Collect-EventLog($t) {
  $dest = Join-Path $live ("evtx_" + ($t.p -replace '[\\/:*?"<>| ]', "_") + ".evtx")
  if (Test-Path $dest) { Add-Row $t $t.p "exported" "shared export" "" "" "" $dest.Substring($root.Length + 1); return }
  & wevtutil.exe epl $t.p $dest 2>$null
  if (Test-Path $dest) { Add-Row $t $t.p "exported" "" (Get-Item $dest).Length "" (Get-FileHash $dest -Algorithm SHA256).Hash.ToLower() $dest.Substring($root.Length + 1) }
  else { Add-Row $t $t.p "absent" "channel not present or not enabled" "" "" "" "" }
}

$targets = @(
__TARGETS__
)

Write-Host "[1/4] volatile state: processes, sockets, DNS cache"
$procs = Get-CimInstance Win32_Process -ErrorAction SilentlyContinue |
  Select-Object ProcessId, ParentProcessId, Name, ExecutablePath, CommandLine, CreationDate
$procs | Export-Csv -NoTypeInformation -Encoding UTF8 (Join-Path $live "processes.csv")
Get-NetTCPConnection -ErrorAction SilentlyContinue |
  Select-Object LocalAddress, LocalPort, RemoteAddress, RemotePort, State, OwningProcess, CreationTime |
  Export-Csv -NoTypeInformation -Encoding UTF8 (Join-Path $live "tcp.csv")
Get-DnsClientCache -ErrorAction SilentlyContinue | Select-Object Entry, Data, TimeToLive |
  Export-Csv -NoTypeInformation -Encoding UTF8 (Join-Path $live "dns_cache.csv")
$tcp = @(Import-Csv (Join-Path $live "tcp.csv") -ErrorAction SilentlyContinue)
$dns = @(Import-Csv (Join-Path $live "dns_cache.csv") -ErrorAction SilentlyContinue)
foreach ($t in $targets | Where-Object { $_.k -eq "process" }) {
  $hit = @($procs | Where-Object { $n = $_.Name; @($t.n) | Where-Object { $n -like ($_ + "*") } })
  Add-Row $t ($t.n -join ", ") ($(if ($hit) { "running" } else { "not-running" })) ("pids " + (($hit | ForEach-Object ProcessId) -join " ")) "" "" "" "live\processes.csv"
}
foreach ($t in $targets | Where-Object { $_.k -eq "network" }) {
  $l = @($tcp | Where-Object { $_.State -eq "Listen" -and ([int]$_.LocalPort) -in @($t.ports) -and ([int]$_.LocalPort) -ne 443 })
  $d = @($dns | Where-Object { $e = $_.Entry; @($t.hosts) | Where-Object { $e -like ("*" + $_) } })
  Add-Row $t (@($t.ports) + @($t.hosts) -join " ") "snapshot" ("listeners " + $l.Count + ", dns hits " + $d.Count) "" "" "" "live\tcp.csv"
}

Write-Host "[2/4] event logs and registry"
foreach ($t in $targets | Where-Object { $_.k -eq "eventlog" }) { Collect-EventLog $t }
foreach ($t in $targets | Where-Object { $_.k -eq "registry" }) { Collect-Registry $t }

Write-Host "[3/4] files"
foreach ($t in $targets | Where-Object { $_.k -eq "path" }) { Collect-Path $t }
foreach ($t in $targets | Where-Object { $_.k -eq "manual" }) { Add-Row $t "" "manual" $t.why "" "" "" "" }

Write-Host "[4/4] manifest"
$finished = (Get-Date).ToUniversalTime()
$self = if ($PSCommandPath) { (Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash.ToLower() } else { "" }
$manifest | Export-Csv -NoTypeInformation -Encoding UTF8 (Join-Path $root "manifest.csv")
[pscustomobject]@{
  case_id=$CaseId; operator=$Operator; host=$env:COMPUTERNAME; elevated=$isAdmin
  started_utc=$started.ToString("o"); finished_utc=$finished.ToString("o")
  script_sha256=$self; collect_secrets=[bool]$CollectSecrets; repo_paths=($RepoPath -join ";")
  home_paths=($homes -join ";")
  generator="ai-dfir-toolkit"
} | ConvertTo-Json | Set-Content -Encoding UTF8 (Join-Path $root "collection.json")
Get-ChildItem $root -Recurse -File | Where-Object { $_.Name -ne "SHA256SUMS" } |
  ForEach-Object { "{0}  {1}" -f (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLower(), $_.FullName.Substring($root.Length + 1) } |
  Set-Content -Encoding ASCII (Join-Path $root "SHA256SUMS")
$zip = $root + ".zip"
Compress-Archive -Path (Join-Path $root "*") -DestinationPath $zip -Force
"{0}  {1}" -f (Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash.ToLower(), (Split-Path $zip -Leaf) | Set-Content -Encoding ASCII ($zip + ".sha256")
$sum = $manifest | Group-Object status | ForEach-Object { "{0} {1}" -f $_.Count, $_.Name }
Write-Host ("done: " + ($sum -join ", "))
Write-Host ("evidence: " + $zip)
'''

SH = r'''#!/usr/bin/env bash
# AI agent artifact triage - generated by ai-dfir-toolkit
# __META__
#
# Run with sudo to reach every user's home. Read-only against the sources.
# Usage:
#   sudo bash __NAME__.sh --case IR-001 --operator you [--out /evidence]
#        [--repo /src/app --repo /src/other] [--home /home/alice] [--collect-secrets]
#        [--max-file-mb 512]
set -u
CASE="case"; OPERATOR="${SUDO_USER:-${USER:-unknown}}"; OUT="/var/tmp/AIDFIR"
COLLECT_SECRETS=0; MAX_MB=512; REPOS=""; HOME_ONLY=""
while [ $# -gt 0 ]; do
  case "$1" in
    --case) CASE="$2"; shift 2 ;;
    --operator) OPERATOR="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --repo) REPOS="$REPOS
$2"; shift 2 ;;
    --home) HOME_ONLY="$HOME_ONLY
$2"; shift 2 ;;
    --collect-secrets) COLLECT_SECRETS=1; shift ;;
    --max-file-mb) MAX_MB="$2"; shift 2 ;;
    *) echo "unknown option $1" >&2; exit 2 ;;
  esac
done
OS_NAME=$(uname -s)
HOSTNAME_=$(hostname 2>/dev/null || uname -n)
STARTED=$(date -u +%Y-%m-%dT%H:%M:%SZ)
ROOT="$OUT/${CASE}_${HOSTNAME_}_$(date -u +%Y%m%dT%H%M%SZ)"
FILES="$ROOT/files"; LIVE="$ROOT/live"
mkdir -p "$FILES" "$LIVE" || exit 1
MANIFEST="$ROOT/manifest.tsv"
printf 'anchor\ttool\tclass\ttemplate\tpath\tstatus\tsize\tmtime_epoch\tsha256\tdest\tnote\n' > "$MANIFEST"
[ "$(id -u)" -eq 0 ] || echo "warning: not root - other users' homes will be unreadable" >&2

if command -v sha256sum >/dev/null 2>&1; then SHA="sha256sum"; else SHA="shasum -a 256"; fi
sha() { $SHA "$1" 2>/dev/null | awk '{print $1}'; }
if [ "$OS_NAME" = "Darwin" ]; then
  fsize() { stat -f %z "$1" 2>/dev/null; }; fmtime() { stat -f %m "$1" 2>/dev/null; }
  HOMES=$(ls -d /Users/* 2>/dev/null | grep -v -e '/Shared$' -e '/Guest$'; echo /var/root)
else
  fsize() { stat -c %s "$1" 2>/dev/null; }; fmtime() { stat -c %Y "$1" 2>/dev/null; }
  HOMES=$(ls -d /home/* 2>/dev/null; echo /root)
fi
# Every home by default; --home narrows collection to the named ones.
[ -n "$HOME_ONLY" ] && HOMES="$HOME_ONLY"

row() { # anchor tool class template path status size mtime sha dest note
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}" "${11}" >> "$MANIFEST"
}

# Every credential location the catalog knows for this OS, not only the picked
# ones. A directory row (~/.claude/) otherwise sweeps a token file into the copy
# and defeats the hash-only rule for secrets.
SECRET_PATTERNS='__SECRETS__'
is_secret() {
  printf '%s\n' "$SECRET_PATTERNS" | while IFS= read -r pat; do
    [ -z "$pat" ] && continue
    case "$1" in $pat) echo yes; break ;; esac
  done
}

collect_file() { # anchor tool class template secret file
  f="$6"; size=$(fsize "$f"); mt=$(fmtime "$f")
  sec="$5"; [ "$sec" = "1" ] || { [ -n "$(is_secret "$f")" ] && sec=1; }
  if [ -n "$size" ] && [ "$size" -gt $((MAX_MB * 1048576)) ]; then
    row "$1" "$2" "$3" "$4" "$f" metadata-only "$size" "$mt" "" "" "larger than ${MAX_MB} MB"; return
  fi
  h=$(sha "$f")
  if [ -z "$h" ]; then row "$1" "$2" "$3" "$4" "$f" error "$size" "$mt" "" "" "unreadable"; return; fi
  if [ "$sec" = "1" ] && [ "$COLLECT_SECRETS" -ne 1 ]; then
    row "$1" "$2" "$3" "$4" "$f" hashed-only "$size" "$mt" "$h" "" "credential: pass --collect-secrets to copy"; return
  fi
  dest="$FILES$f"; mkdir -p "$(dirname "$dest")"
  if cp -p "$f" "$dest" 2>/dev/null; then
    [ "$(sha "$dest")" = "$h" ] && st=copied || st=copied-hash-mismatch
    row "$1" "$2" "$3" "$4" "$f" "$st" "$size" "$mt" "$h" "files$f" ""
  else
    row "$1" "$2" "$3" "$4" "$f" error "$size" "$mt" "$h" "" "copy failed"
  fi
}

expand() { # concrete pattern -> matching paths, one per line
  p="$1"
  case "$p" in
    *[\*\?]*)
      base="${p%%[\*\?]*}"; base="${base%/*}"; rest="${p#"$base"/}"
      depth=$(printf '%s' "$rest" | awk -F/ '{print NF}')
      [ -d "$base" ] && find "$base" -mindepth "$depth" -maxdepth "$depth" -path "$p" 2>/dev/null ;;
    *) [ -e "$p" ] && printf '%s\n' "$p" ;;
  esac
}

P() { # anchor tool class secret template
  case "$5" in
    *"{HOME}"*) bases="$HOMES"; tok="{HOME}" ;;
    *"{REPO}"*) bases="$REPOS"; tok="{REPO}" ;;
    *) bases="-"; tok="" ;;
  esac
  printf '%s\n' "$bases" | while IFS= read -r b; do
    [ -z "$b" ] && continue
    if [ -n "$tok" ]; then b="${b%/}"; pat=$(printf '%s' "$5" | awk -v t="$tok" -v r="$b" '{i=index($0,t); print substr($0,1,i-1) r substr($0,i+length(t))}'); else pat="$5"; fi
    found=0
    expand "$pat" | while IFS= read -r m; do
      if [ -d "$m" ]; then find "$m" -type f 2>/dev/null | while IFS= read -r f; do collect_file "$1" "$2" "$3" "$5" "$4" "$f"; done
      else collect_file "$1" "$2" "$3" "$5" "$4" "$m"; fi
    done
    [ -z "$(expand "$pat" | head -n 1)" ] && row "$1" "$2" "$3" "$5" "$pat" absent "" "" "" "" ""
  done
}
PROC() { row "$1" "$2" process "$3" "$3" snapshot "" "" "" "live/processes.txt" "$(grep -i -c -E "$3" "$LIVE/processes.txt" 2>/dev/null) matching lines"; }
NET() { row "$1" "$2" network "$3" "$3" snapshot "" "" "" "live/sockets.txt" "ports and hosts to review in the socket and DNS snapshots"; }
MANUAL() { row "$1" "$2" "$3" "" "" manual "" "" "" "" "$4"; }

echo "[1/3] volatile state: processes and sockets"
ps -axo pid,ppid,user,lstart,command > "$LIVE/processes.txt" 2>/dev/null || ps -ef > "$LIVE/processes.txt"
if [ "$OS_NAME" = "Darwin" ]; then
  lsof -nP -iTCP -iUDP > "$LIVE/sockets.txt" 2>/dev/null
else
  (ss -tunap 2>/dev/null || netstat -tunap 2>/dev/null) > "$LIVE/sockets.txt"
fi

echo "[2/3] targets"
__TARGETS__

echo "[3/3] manifest"
SELF=""; [ -f "$0" ] && SELF=$(sha "$0")
cat > "$ROOT/collection.json" <<EOF_META
{"case_id":"$CASE","operator":"$OPERATOR","host":"$HOSTNAME_","os":"$OS_NAME","uid":$(id -u),
 "started_utc":"$STARTED","finished_utc":"$(date -u +%Y-%m-%dT%H:%M:%SZ)",
 "script_sha256":"$SELF","collect_secrets":$COLLECT_SECRETS,"generator":"ai-dfir-toolkit",
 "homes":"$(printf '%s' "$HOMES" | tr '\n' ';')"}
EOF_META
(cd "$ROOT" && find . -type f ! -name SHA256SUMS -print | while IFS= read -r f; do printf '%s  %s\n' "$(sha "$f")" "${f#./}"; done > SHA256SUMS)
tar -czf "$ROOT.tar.gz" -C "$(dirname "$ROOT")" "$(basename "$ROOT")" && printf '%s  %s\n' "$(sha "$ROOT.tar.gz")" "$(basename "$ROOT").tar.gz" > "$ROOT.tar.gz.sha256"
echo "done: $(tail -n +2 "$MANIFEST" | cut -f6 | sort | uniq -c | tr '\n' ' ')"
echo "evidence: $ROOT.tar.gz"
'''
