#!/usr/bin/env python3
"""Resolve every ATLAS and ATT&CK id in the catalog against real framework data.

The schema validates these ids by shape only - `^AML\\.T[0-9]{4}(\\.[0-9]{3})?$`
and `^T[0-9]{4}(\\.[0-9]{3})?$` - so `AML.T9999` passes CI today, and so does a
technique MITRE deprecated three releases ago. Shape is not existence.

    python scripts/validate_techniques.py           # gate, writes nothing
    python scripts/validate_techniques.py --check   # same, explicit
    python scripts/validate_techniques.py --refresh # re-pin from upstream

Validation runs offline against `schema/technique-ids.json`, which is vendored
and pinned. It is deliberately not fetched at gate time: a gate that silently
follows upstream lets a MITRE rename break the build with no diff to explain it,
and CI that needs the network fails for reasons that have nothing to do with the
change under test. `--refresh` is the only thing that touches the network, and it
rewrites the pin so the bump shows up in review as a diff someone signs off on.

Two upstream traps, both of which produce a plausible wrong answer rather than an
error, and both of which this script exists to avoid repeating:

  ATLAS ships a `dist/ATLAS.yaml` that opens by declaring itself deprecated. It
  carries fewer techniques than the current release. Validating against it
  reports success while checking stale data, so `--refresh` reads
  `dist/manifest.yaml` and takes the newest release path instead.

  The ATLAS YAML uses anchors, so techniques exist that never appear as literal
  text in the file. Grepping it undercounts by roughly sixteen and would reject
  valid ids as unknown. Parse it, never grep it.
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
import urllib.request
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PINNED = ROOT / "schema" / "technique-ids.json"

ATLAS_MANIFEST = "https://raw.githubusercontent.com/mitre-atlas/atlas-data/main/dist/manifest.yaml"
ATLAS_BASE = "https://raw.githubusercontent.com/mitre-atlas/atlas-data/main/dist/"
ATTACK_INDEX = "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/index.json"


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=180) as r:
        return r.read()


def version_key(s: str) -> tuple:
    """Numeric version sort, component-wise.

    Two ways to get this wrong, both of which pick a real-looking older release
    rather than raising: sorting as strings puts ATT&CK 9.0 above 17.0, and
    stripping the separator first turns ATLAS 2025.11.2 into 2025112, which
    beats 2026.07 at 202607. Compare tuples of ints, per component.
    """
    try:
        return tuple(int(x) for x in str(s).split("."))
    except ValueError:
        return (0,)


def refresh() -> dict:
    manifest = yaml.safe_load(fetch(ATLAS_MANIFEST).decode("utf-8"))
    newest = max(manifest, key=lambda r: version_key(str(r["release"])))
    path = newest["versions"][0]["path"]
    atlas_doc = yaml.safe_load(fetch(ATLAS_BASE + path).decode("utf-8"))

    atlas: dict[str, str] = {}

    def walk(node) -> None:
        if isinstance(node, dict):
            ident = node.get("id")
            if isinstance(ident, str) and ident.startswith("AML.T"):
                atlas[ident] = node.get("name", "")
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(atlas_doc)

    index = json.loads(fetch(ATTACK_INDEX))
    enterprise = next(c for c in index["collections"] if c["name"] == "Enterprise ATT&CK")
    latest = max(enterprise["versions"], key=lambda v: version_key(v["version"]))
    bundle = json.loads(fetch(latest["url"]))

    attack: dict[str, str] = {}
    retired: list[str] = []
    for obj in bundle.get("objects", []):
        if obj.get("type") != "attack-pattern":
            continue
        for ref in obj.get("external_references", []):
            if ref.get("source_name") == "mitre-attack" and ref.get("external_id"):
                ident = ref["external_id"]
                attack[ident] = obj.get("name", "")
                if obj.get("x_mitre_deprecated") or obj.get("revoked"):
                    retired.append(ident)

    return {
        "_comment": "Generated by scripts/validate_techniques.py --refresh. Do not hand-edit.",
        "retrieved": date.today().isoformat(),
        "atlas": {
            "release": str(newest["release"]),
            "source": ATLAS_BASE + path,
            "techniques": dict(sorted(atlas.items())),
        },
        "attack": {
            "version": latest["version"],
            "source": latest["url"],
            "techniques": dict(sorted(attack.items())),
            "retired": sorted(set(retired)),
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="validate only - the default, accepted for symmetry with the other gates")
    ap.add_argument("--refresh", action="store_true",
                    help="re-pin schema/technique-ids.json from upstream (network)")
    ap.add_argument("--advise", action="store_true",
                    help="also list parents whose subtechniques might be a more precise mapping")
    args = ap.parse_args()

    if args.refresh:
        data = refresh()
        # newline="\n" explicitly: this file is generated on whatever platform
        # the refresher happens to run on, and the repo keeps generated output
        # byte-identical across platforms.
        with open(PINNED, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
        print(f"ATLAS   {data['atlas']['release']:>8}  "
              f"{len(data['atlas']['techniques'])} techniques")
        print(f"ATT&CK  {data['attack']['version']:>8}  "
              f"{len(data['attack']['techniques'])} techniques "
              f"({len(data['attack']['retired'])} deprecated or revoked)")
        print(f"pinned to {PINNED.relative_to(ROOT)}")
        return 0

    if not PINNED.exists():
        print(f"{PINNED.relative_to(ROOT)} is missing - run --refresh", file=sys.stderr)
        return 1

    pin = json.loads(PINNED.read_text(encoding="utf-8"))
    atlas = pin["atlas"]["techniques"]
    attack = pin["attack"]["techniques"]
    retired = set(pin["attack"]["retired"])

    # Parent -> subtechniques, built once. Scanning every id per technique per
    # entry re-walks the whole framework a few hundred times for one lookup.
    children: dict[str, list[str]] = {}
    if args.advise:
        for ident in atlas:
            # rpartition, not partition: AML.T0051.000 splits on the LAST dot.
            # Splitting on the first one makes every parent "AML" and silently
            # produces zero advisories rather than an error.
            parent, _, sub = ident.rpartition(".")
            if sub and len(sub) == 3 and sub.isdigit():
                children.setdefault(parent, []).append(ident)
        for subs in children.values():
            subs.sort()

    problems: list[str] = []
    advisories: list[str] = []

    for path in sorted(glob.glob(str(ROOT / "catalog" / "*.yml"))):
        entry = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        eid = entry.get("id", Path(path).name)

        for ident in entry.get("atlas_techniques") or []:
            if ident not in atlas:
                problems.append(f"{eid}: atlas_techniques {ident} is not in ATLAS "
                                f"{pin['atlas']['release']}")
            elif args.advise:
                subs = children.get(ident, [])
                if subs:
                    advisories.append(
                        f"{eid}: {ident} ({atlas[ident]}) has {len(subs)} subtechnique(s) - "
                        f"a more precise mapping may exist: {', '.join(subs)}")

        for ident in entry.get("attack_techniques") or []:
            if ident not in attack:
                problems.append(f"{eid}: attack_techniques {ident} is not in Enterprise "
                                f"ATT&CK {pin['attack']['version']}")
            elif ident in retired:
                problems.append(f"{eid}: attack_techniques {ident} ({attack[ident]}) is "
                                f"deprecated or revoked in {pin['attack']['version']}")

    print(f"pinned: ATLAS {pin['atlas']['release']} ({len(atlas)} techniques), "
          f"ATT&CK {pin['attack']['version']} ({len(attack)} techniques), "
          f"retrieved {pin['retrieved']}")

    if advisories:
        print(f"\n{len(advisories)} advisory - not failures, --advise only:")
        for line in advisories:
            print(f"  [SUB]  {line}")

    if problems:
        print()
        for line in problems:
            print(f"  [BAD]  {line}", file=sys.stderr)

    print(f"\n{len(problems)} problem(s).")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
