#!/usr/bin/env python3
"""Emit the verification worklist: what still needs checking, and against what.

Derived from the catalog rather than hand-maintained, for the usual reason - a
typed list of "things to verify" is correct on the day it is written and wrong
by the next merge. Regenerate it instead of editing it.

    python scripts/verification_worklist.py            > docs/WORKLIST.md
    python scripts/verification_worklist.py --summary  # counts only

An entry lands on the list when it has never been verified, or when it is rated
`medium` or `low`. Each block prints the paths a verifier has to confirm and the
references already on file, so the work is "open these, check those" rather than
"go and research this tool from scratch".
"""
from __future__ import annotations

import argparse
import glob
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent


def locators(entry: dict):
    """Every claim in an entry that a documentation check could confirm."""
    for a in (entry.get("artifacts") or {}).get("disk") or []:
        yield a.get("confidence", ""), "disk", a.get("path", "")
    for a in (entry.get("artifacts") or {}).get("registry") or []:
        yield a.get("confidence", ""), "registry", a.get("key", "")
    for a in (entry.get("artifacts") or {}).get("network") or []:
        yield a.get("confidence", ""), "network", a.get("indicator", "")
    for c in entry.get("credentials") or []:
        yield c.get("confidence", ""), "credential", c.get("location", "")
    for m in entry.get("mcp") or []:
        if m.get("mechanism") == "config-file":
            yield m.get("confidence", ""), "mcp", m.get("config_path", "")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", action="store_true")
    args = ap.parse_args()

    entries = [yaml.safe_load(Path(f).read_text(encoding="utf-8"))
               for f in sorted(glob.glob(str(ROOT / "catalog" / "*.yml")))]

    never = [e for e in entries if not e.get("last_verified")]
    weak = [e for e in entries
            if e.get("last_verified") and e.get("confidence") in ("medium", "low")]

    if args.summary:
        print(f"never verified : {len(never)}")
        print(f"medium or low  : {len(weak)}")
        print(f"total on list  : {len(never) + len(weak)}")
        return 0

    print("# Verification worklist\n")
    print("Generated by `scripts/verification_worklist.py`. Do not edit - regenerate.\n")
    print("Read `docs/REVERIFICATION.md` first, and in particular the rule about")
    print("`last_verified`: it means somebody checked, so do not set it from a search")
    print("engine's summary of a page. Open the page.\n")
    print("For each entry below: confirm each path against the vendor's own")
    print("documentation, correct what is wrong, then set `last_verified` and raise")
    print("`confidence` only as far as the sourcing actually supports. Log every")
    print("correction in `docs/VERIFICATION.md` with its basis.\n")

    for title, group, why in (
        ("Never verified", never,
         "No `last_verified` at all. These are listed on every `validate.py` run."),
        ("Medium or low confidence", weak,
         "Verified once, but the sourcing has not supported an upgrade. "
         "Issue #8 tracks these."),
    ):
        print(f"\n## {title} — {len(group)}\n")
        print(f"{why}\n")
        for e in sorted(group, key=lambda x: x["id"]):
            cloud = "cloud" in [o.lower() for o in (e.get("supported_os") or [])]
            print(f"### {e['id']} — {e['name']}\n")
            print(f"- entry confidence: `{e.get('confidence')}`"
                  f"{' · **cloud-hosted, no endpoint paths to check**' if cloud else ''}")
            if e.get("status"):
                print(f"- status: `{e['status']}`")
            refs = e.get("references") or []
            if refs:
                print("- check against:")
                for r in refs:
                    print(f"    - [{r.get('title', r.get('url'))}]({r.get('url')})")
            else:
                print("- **no references on file** - find the vendor's own page first")
            rows = [(c, k, v) for c, k, v in locators(e) if v]
            if rows:
                print(f"- {len(rows)} claim(s) to confirm:")
                for conf, kind, val in rows:
                    mark = "  " if conf == "high" else " <-"
                    print(f"    - `{conf or '?'}`{mark} {kind}: `{val}`")
            print()

    print("\n## When you are done\n")
    print("Run the full gate set. CI runs eight checks and a partial local run has")
    print("already let two failures through:\n")
    print("```bash")
    print("cd artifacts")
    print("python scripts/validate.py")
    print("python scripts/build_site.py --check")
    print("python scripts/data_sources.py")
    print("python scripts/export_kape.py --check")
    print("python scripts/export_velociraptor.py --check")
    print("python scripts/normalize_notes.py --check")
    print("cd .. && python collectors/gen_credential_targets.py --check")
    print("python collectors/check_target_drift.py")
    print("python artifacts/scripts/validate_mappings.py")
    print("```\n")
    print("Regenerate all five feeds in the same commit as any catalog change:")
    print("`export.py`, `export_forensicartifacts.py`, `export_kape.py`,")
    print("`export_velociraptor.py`, and `collectors/gen_credential_targets.py`.")
    print("Running a generator is not the same as confirming it - only `--check` is.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
